version: '3.8'

services:
  netvexa-mvp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=sqlite+aiosqlite:///app/data/netvexa_mvp.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped